"""Alembic environment — async-aware.

This file replaces the default sync template generated by `alembic init`.
It plugs the project's existing settings + Base.metadata into Alembic so:

  - autogen sees every model that's imported at module load time
  - the URL comes from settings.DATABASE_URL (not alembic.ini's placeholder)
  - migrations run through asyncpg via SQLAlchemy 2.0 async APIs

Two flows:

  - **offline** (`alembic upgrade head --sql`) — emits SQL without connecting.
    Useful for review.
  - **online** — connects to the DB and runs `op.execute(...)` for each
    migration. Used by the entrypoint on container start.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Project imports — these MUST register every model with Base.metadata,
# so any new model added under db/models.py gets picked up by autogen.
from config import settings  # noqa: E402
from db.models import Base  # noqa: E402

# Alembic Config object — gives access to alembic.ini values.
config = context.config

# Override the placeholder URL from alembic.ini with the real one. Convert
# the asyncpg-flavored URL to a sync-flavored one only when running `--sql`
# offline; the online path uses async natively.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _offline_url() -> str:
    """Strip the asyncpg driver prefix for offline SQL emission.

    asyncpg URLs look like:
        postgresql+asyncpg://user:pw@host/db
    Alembic's offline mode just needs the dialect, not a real connection.
    """
    url = settings.DATABASE_URL
    return url.replace("postgresql+asyncpg://", "postgresql://", 1)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emits SQL to stdout."""
    context.configure(
        url=_offline_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Sync migration runner — invoked from the async helper via run_sync."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Connect via asyncpg, then drop into the sync runner via run_sync.

    `async_engine_from_config` reads the [alembic] section of alembic.ini —
    we already overrode sqlalchemy.url above, so it picks up our async URL.
    """
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Online entry point — bridges Alembic's sync API to asyncpg via asyncio."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
